version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ContactManager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ContactManager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
